### ISSUE TITLE
Release v4 as Baumeister v1.0.0

### ISSUE THREAD

**Issue by lfuelling** [micromata/baumeister#183]
The links and code snippets in the README are not working anymore for the master branch. #180 missed those steps 😄

**Comment by mischah** [comment]
Thanks. Valid points.

It’s not possible to rename npm packages (because of the potential to break peoples stuff)

But we now have a plan how to release Baumeister 1.0:

# Yeoman Generator

## npm

- Publish `generator-baumeister` v1.0.0
- Deprecate `generator-bootstrap-kickstart` 
  - Add link to `generator-baumeister` within the deprecation message

## GitHub Repo

- Create new repo `micromata/generator-baumeister`
  - Release `v1.0.0` without Bootstrap Kickstart Git history
- Deprecate `micromata/generator-bootstrap-kickstart` 
  Add deprecation message and link to `generator-baumeister` Repo
  - Master branch will have the latest `v3` Release
  - We might keep the `v4-dev` Branch for a while to remain `v4` Git history

_We are Going to handle the release of `micromata/baumeister` the same way_ 

---

I just have to check if its possible to keep the existing GitHub stars by:

- Renaming `micromata/generator-bootstrap-kickstart` to `micromata/generator-baumeister`
- Create a »new« Repo `micromata/generator-bootstrap-kickstart` afterwards

**Comment by mischah** [comment]
@lfuelling 

Does this makes sense to you?
Did I miss something important?

**Comment by lfuelling** [comment]
No, it makes perfect sense.

**Comment by mischah** [comment]
> I just have to check if its possible to keep the existing GitHub stars by:
>
>- Renaming `micromata/generator-bootstrap-kickstart` to `micromata/generator-baumeister`
>- Create a »new« Repo `micromata/generator-bootstrap-kickstart` afterwards

Tested with private repos: It works 🎉

**Comment by mischah** [comment]
It’s done 🎉

https://github.com/micromata/baumeister/releases
